# Setup
title:               Lukej2680
tagline:             'Tech Blog'
description:         'A personal blog for all things tech related.'
url:                 https://lukej2680.github.io #http://lanyon.getpoole.com
baseurl:             /
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
