# Setup
title:               Lukej2680
tagline:             'Tech Blog'
description:         'A personal blog relating to all things tech related.'
url:                 https://lukej2680.github.io #http://lanyon.getpoole.com
baseurl:             /
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              William Puppo
  url:               https://www.linkedin.com/in/william-puppo-4a2996154/
  email:             wjpuppo@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
